version: "3.7"

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: yarn dev
